### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by raphaelbastide** [litewrite/litewrite#221] opened 2015-03-15 13:59 UTC
I tried to install Litewrite on my [server](http://lab.raphaelbastide.com/note/) (temporary copy) and it seams not to work properly. The web dev console outputs: `remoteStorageDocuments.privateList is not a function`
Did I miss something during the installation ? I didn’t found any installation instructions so I guess it doesn’t need any special requirement right?

**Comment by jancborchardt** [comment] 2015-03-17 11:50
@skddc @michielbdejong @galfert do you have any ideas about this issue regarding remoteStorage?

**Comment by skddc** [comment] 2015-03-17 11:59
Is this still a thing? The code looks wrong, as it should be `remoteStorage.documents`.

**Comment by raphaelbastide** [comment] 2015-03-18 09:37
I have more. It is weird. Each time I refresh I get diffent errors, and sometimes the “Write” title on the left displays, sometimes not:
Error 1

    Error: Mismatched anonymous define() module: function () {
	if (!Object.keys) {
		Object.keys = (function () {
			var hasOwnProperty = Object.prototype.hasOwnProperty,
				hasDontEnumBug = !({toString: null}).propertyIsEnumerable('toString'),
				dontEnums = [
					'toString',
					'toLocaleString',
					'valueOf',
					'hasOwnProperty',
					'isPrototypeOf',
					'propertyIsEnumerable',
					'constructor'
				],
				dontEnumsLength = dontEnums.length;

			return function (obj) {
				if (typeof obj !== 'object' && typeof obj !== 'function' || obj === null) {
					throw new TypeError('Object.keys called on non-object');
				}

				var result = [];

				for (var prop in obj) {
					if (hasOwnProperty.call(obj, prop)) {
						result.push(prop);
					}
				}

				if (hasDontEnumBug) {
					for (var i=0; i < dontEnumsLength; i++) {
	 require.js:161:12
	Error: Load timeout for modules: i18n!nls/lang_unnormalized2,i18n!nls/lang_unnormalized3,i18n!nls/lang

Error 2

    TypeError: plugin.load is not a function

Error 3, when I click on "+"

    EditorView is not a constructor

Error 4, when I type something in the right part 

    remoteStorageDocuments.privateList is not a function

**Comment by skddc** [comment] 2015-03-18 09:52
It looks like some files didn't load correctly. I'm not famililar with the details of that, though.

@jorin-vogel Can you help?

**Comment by raphaelbastide** [comment] 2015-05-26 09:14
Anything fresh about this issue?
I really want to use this app :-) :pencil2:

**Comment by jancborchardt** [comment] 2015-05-27 13:14
@jorin-vogel can you help, or maybe document some stuff so another person can take over? :)

cc @michielbdejong @skddc would be good if we can solve this.

**Comment by skddc** [comment] 2015-05-27 13:19
I'm following this, but I can't help any further at the moment. Also, the author should probably update the remoteStorage.js library version before trying to fix old bugs.

**Comment by jorin-vogel** [comment] 2015-05-28 00:55
I look into it on the weekend. Haven't touched Litewrite for quiet a while. 
Let's see if we can just update remoteStorage.js.

**Comment by skddc** [comment] 2015-05-28 09:43
\o/

**Comment by jorin-vogel** [comment] 2015-05-30 06:00
@raphaelbastide Sorry, for the late feedback. Unfortunately we are not working much on Litewrite lately and it's difficult to find those kind of bugs with all the magic happening behind remotestorage..

Which version did you put on your server? It should just work with any static file server .
Could you try using a built version? (as described in the readme: https://github.com/litewrite/litewrite#building-the-production-version)
Unfortunately I can't reproduce the issue.

**Comment by jorinvo** [comment] 2015-11-08 17:19
@raphaelbastide I'm so sorry for this issue being stuck so long.
I also ran into issues with Litewrite. And I think it was related to the require.js setup.
Now I'm back working on Litewrite and with this PR #255 we gonna move to webpack.
I have no issues more after that.

If you want to try it right now you can checkout the `setup` branch.
Or you just wait a little longer and we get this merged and tested.

**Closed by jorinvo** 2015-11-08 17:19 UTC
Labels: issue
