### ISSUE TITLE
Using the browsers CTRL-S to save the current document should produce the current doc in some format

### ISSUE THREAD

**Issue by silverbucket** [litewrite/litewrite#182] opened 2013-09-16 13:10 UTC
Right now, when you use the browsers save page function, it generates a file that contains the generic "welcome to litewrite" text, instead of the contents of the current note you are viewing.

**Comment by jorinvo** [comment] 2015-11-13 09:00
This might be helpful since we can't use the default save behavior of the browser:
 https://github.com/eligrey/FileSaver.js/

Also think saving as .txt file is the right way. 
(Since switching to textarea we don't support support rich text anyway)

**Comment by jancborchardt** [comment] 2015-11-16 13:14
Is a dialog akin to »Export« really what people expect when they press Ctrl-S to save? Since Litewrite is an app, I would expect a force save (so basically doing nothing since we have autosave ;) instead of being interrupted. We could use Ctrl-E or something for exporting as txt, and then there’s Ctrl-P for printing (export to PDF).

**Comment by jorinvo** [comment] 2015-11-16 14:28
Also not clear what a save as .txt should be useful for.
If you just want the plain text you can just copy and paste it right from the editor...

@jancborchardt maybe you are right. We could just leave it for now. 
The first person who really needs it can send a PR for a shortcut :wink:

**Comment by jancborchardt** [comment] 2015-11-16 14:36
Yeah. At the same time I would say we should suppress the Ctrl-S shortcut to not show the »Save as« dialog since that takes one out of the flow.

**Comment by jorinvo** [comment] 2015-11-16 14:50
Hm, on the other hand it's kind of cool that you can save `litewrite.html` and you have a complete version of litewrite on your computer...

I think it would be really awesome if we could inline the missing assets into the built version and have perfect copy of litewrite just downloadable like this.
(Missing files are `litewrite.js`, `litewrite.css`, `noise.png`, `share.svg` and `Alegreya-Regular.ttf`)
Webpack can do the inlining automatically for us. 
The `share.svg` icon we could maybe replace with unicode. But we have to work on sharing anyways.
And maybe we don't even need the font?
I read some interesting stuff about using system fonts for web pages (See https://medium.com/@mwichary/system-shock-6b1dc6d6596f and http://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/).

**Comment by skddc** [comment] 2015-11-16 14:53
@jorinvo The problem is that in order for Web Storage to work, you need an origin, so you can't just open a and HTML file in your browser.

**Comment by jancborchardt** [comment] 2015-11-16 14:58
> Hm, on the other hand it's kind of cool that you can save litewrite.html and you have a complete version of litewrite on your computer...

Are you sure people realize that you can do that, and then will go ahead and do it? Not even I would expect it. ;) Better to do a dedicated desktop version by wrapping it with Electron maybe?

**Comment by jorinvo** [comment] 2015-11-16 14:59
@jancborchardt we can tell people about it :)

@skddc I see... So saving doesn't work unless you put it on a webserver...
But it would work by using localstorage ...

**Comment by skddc** [comment] 2015-11-16 15:02
> @skddc I see... So saving doesn't work unless you put it on a webserver...

Yes, you'll need to start one for that directory. Easy for developers and power users, but not for anyone else.

> But it would work by using localstorage ...

Nope, that's what you need the origin for: http://www.w3.org/TR/webstorage/#dom-localstorage

**Comment by jorinvo** [comment] 2015-11-16 15:12
@skddc strange. When I tried it in Chrome and Firefox it still works...

**Comment by skddc** [comment] 2015-11-16 15:19
That's not a trusted origin for Web Storage afaik. It should work, but only for one session, as rs.js should use the in-memory caching backend when nothing else is available. Did you try closing the window and opening the same `file://` URL again?

**Comment by jancborchardt** [comment] 2015-11-16 15:23
@jorinvo my worry is that the Ctrl-S shortcut is usually for saving the current document. Sure websites you should be able to save, but for a web app it’s just a bad default. In Etherpad, Litewrite or any online text editor it’s always confusing when you press Ctrl-S out of habit and your expectation of the document getting saved is interrupted by the dialog popping up.

Having a way to save Litewrite on one’s machine might be interesting, but I’d say it’s a different discussion from the Ctrl-S shortcut.

**Comment by jorinvo** [comment] 2015-11-16 15:25
@skddc yes, it worked also also after closing. All I tried was using the console: `localStorage.bla = 132` and then `localStorage.bla` was still `"123"`.

@jancborchardt you are right. 
We could disable Ctrl-S and still bundle everything in one file.
People crazy enough to use litewrite from a local web server can find another way to save the file :wink:

**Closed** 2015-11-17 13:56 UTC
Labels: enhancement
