### ISSUE TITLE
Pressing any key scrolls text to the bottom

### ISSUE THREAD

**Issue by Miserlou** [litewrite/litewrite#277] opened 2017-05-16 18:09 UTC
Really annoying one!

When I have the cursor position here (after "being):
<img width="1391" alt="screen shot 2017-05-16 at 2 05 55 pm" src="https://cloud.githubusercontent.com/assets/139987/26121031/dca08a12-3a40-11e7-8a95-cd240d30cf8f.png">

Pressing any key then insta-scrolls the page and the cursor to the bottom of the page!:
<img width="1391" alt="screen shot 2017-05-16 at 2 06 53 pm" src="https://cloud.githubusercontent.com/assets/139987/26121128/3160c35a-3a41-11e7-8dc1-353ee5d22d32.png">

This essentially makes Litewrite unusable for me. I have no idea why this is happening all of a sudden. :(

**Comment by Miserlou** [comment] 2017-05-16 18:10
Confirming that this also happens in Chrome, however it scrolls to near the center, not the exact bottom.

**Comment by Miserlou** [comment] 2017-05-16 18:14
Not sure if related or not, but pressing (Command + Z), expecting an undo, causes a scroll to the top of the document.

**Comment by jorinvo** [comment] 2017-05-16 18:23
Hi @Miserlou, thanks for reporting this.
Unfortunately I don't have time at the moment to look into this. 
You can check if the same issue occurs on https://litewrite.github.io/litewrite.

**Comment by Miserlou** [comment] 2017-05-16 18:37
Seems like it still happens there. Thanks anyway!

**Comment by jorinvo** [comment] 2017-08-04 15:20
@Miserlou I finally got around to make some changes on Litewrite. I can't reproduce the issue anymore. Would you mind checking if you still get this behavior? (Also make sure your browser cache is cleared) 
Thank you!

**Comment by jorinvo** [comment] 2017-08-31 23:13
I'll close this for now. Feel to reopen, if anyone can still reproduce it.

**Closed by jorinvo** 2017-08-31 23:13 UTC
Labels: issue
