### ISSUE TITLE
Having a delete button for the written note on the sidebar

### ISSUE THREAD

**Issue by sudheesh001** [litewrite/litewrite#283] opened 2017-10-24 01:27 UTC
I am loving litewrite and think it's a great tool. However, It took me a little time to figure out that to delete the note being shown on the left sidebar all I had to do was to completely clear the content in the note. Is there a reason why there is no `delete/trash` button on the left sidebar available on hovering over the text? I believe that'll make the experience much better.

**Comment by jorinvo** [comment] 2017-10-24 12:34
This has been requested before. It is definitely difficult at the moment to figure out deleting.
Would also need to have a confirm for the deletion. That's easier than implementing undo. Simply using `window.confirm()` would be a good start.

Pull Requests welcome :)

**Comment by jorinvo** [comment] 2017-11-06 17:48
I am so sorry @sudheesh001 I just realized I *did* implement this (see https://github.com/litewrite/litewrite/commit/0a7e994ba467bc5165f7193640931603e8275a5e).
Seems like it is not available on [litewrite.net](https://litewrite.net) but it definitely works on [litewrite.github.io/litewrite](https://litewrite.github.io/litewrite).

@skddc any ideas why litewrite.net is not updating? I pushed to 5apps but can't see any changes.

![screen shot 2017-11-06 at 18 47 09](https://user-images.githubusercontent.com/738978/32455601-02303c4e-c323-11e7-9be0-e94c03046a3b.png)

**Comment by raucao** [comment] 2017-11-06 17:52
<del>If it's using AppCache, then you'll have to reload twice (once for the changes to be downloaded in the background, second time for actually seeing them).</del> Sorry, didn't see that the change is months old.

**Comment by jorinvo** [comment] 2017-11-06 17:55
@skddc I hard-reloaded many times. Even tried incognito and different browser..
Can there be any issues that we create our own `service-worker.js` and `cache.manifest`? 
I did disable the ones from 5apps.

![screen shot 2017-11-06 at 18 54 28](https://user-images.githubusercontent.com/738978/32455875-f37fff9e-c323-11e7-8097-dae6df8f744b.png)

**Comment by raucao** [comment] 2017-11-06 17:56
I don't know what your ServiceWorker does, but yes, it could withhold updates if it's buggy. You can try deleting the SW cache as well, but it looks to me like that's not the cause. I'm checking...

**Comment by jorinvo** [comment] 2017-11-06 18:03
@skddc using the same serviceworker on github.io and seems to work fine. Since it also doesn't work in a completely new browser and new session, I am afraid the issue is something else.

**Comment by raucao** [comment] 2017-11-06 21:21
@jorinvo I'm now seeing a commit from August as the last SHA on 5apps. Could you contact me on IRC or XMPP or something? (raucao on Freenode IRC, or sebastian@kip.pe on XMPP)

**Comment by jorinvo** [comment] 2017-11-06 21:41
We solved the issue. litewrite.net has a new version now, also supporting *delete*.
I'll close this issue. Let me know if you  run into any other issues!

**Closed as completed by jorinvo** 2017-11-06 21:41 UTC
Labels: enhancement
